# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Uploads build to Browserstack's app automate and app live and runs all the tests on uploaded app."
  lane :upload_test do |options|

    # Uploads app to BrowserStack app automate.
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: options[:path]
    )

    # Uploads app to BrowserStack app live.
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: options[:path]
    )
    gradle(task: "test")
  end

  desc "Build app"
  lane :build do
    gradle(task: "clean")
    gradle(
      task: "assemble",
      flavor: "Free",
      build_type: "Debug"
    )

    APK_OUTPUT_PATH = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    AAB_OUTPUT_PATH = "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"

    # upload_test(path: APK_OUTPUT_PATH)
  end
end
